/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:e61daa32-ab58-45a4-b193-34cfc8ecc113",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_pHga1nCvn",
    "aws_user_pools_web_client_id": "7qi9p52kjml4lpt49jkmh094li",
    "oauth": {}
};


export default awsmobile;
